language: python
sudo: false
branches:
  only:
    - master

matrix:
  include:
    - python: 3.6
      env: NUMBA_TEST=false
    - python: 3.6
      env: NUMBA_TEST=true
    - python: 3.7
      dist: xenial
      sudo: true
      env: NUMBA_TEST=false
    - python: 3.7
      dist: xenial
      sudo: true
      env: NUMBA_TEST=true

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda config --add channels conda-forge
  - conda config --set channel_priority strict
  - conda create -y -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env

install:
  - conda install --yes pip
  - conda install --yes --file requirements.txt
  - pip install -r requirements_tests.txt
  - if "$NUMBA_TEST"; then
      conda install --yes numba;
    fi

script:
  - python setup.py sdist >/dev/null
  - python setup.py install
  - nosetests --verbose --with-coverage --cover-package=mapclassify;

notifications:
    email:
        recipients:
            - sjsrey@gmail.com
            - levi.john.wolf@gmail.com
            - weikang9009@gmail.com
        on_success: change
        on_failure: always

after_success:
  - coveralls
